# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

[border]
radius=12
width=3

[main]
include=~/.config/fuzzel/themes.ini
font=Iosevka Nerd Font Mono:size=11
icon-theme=Papirus-Dark
icons-enabled=yes
layer=overlay
line-height=16
terminal=kitty
