include                       ~/.config/kitty/theme.conf

background_opacity            0.95
background_blur               1
font_family                   maple Mono NF CN
transparent_background_colors black@0

bell_on_tab                   " "
confirm_os_window_close       -1
copy_on_select                clipboard
draw_minimal_borders          yes
focus_follows_mouse           yes
hide_window_decorations       yes
paste_actions                 quote-urls-at-prompt,confirm,confirm-if-large
pointer_shape_when_grabbed    arrow
strip_trailing_spaces         smart
window_border_width           2px
window_margin_width           2
window_padding_width          2

active_border_color           cyan
bell_border_color             red
inactive_border_color         gray
inactive_text_alpha           0.6

cursor_shape                  beam
cursor_trail                  1
cursor_trail_start_threshold  0
show_hyperlink_targets        yes
underline_hyperlinks          hover

tab_bar_edge                  bottom
tab_bar_align                 left
tab_bar_margin_height         14.0 0.0
tab_bar_min_tabs              1
tab_bar_background            none
tab_bar_margin_color          none
tab_bar_style                 powerline
tab_powerline_style           slanted
tab_activity_symbol           ""
tab_title_template            "{activity_symbol} {tab.last_focused_progress_percent} {index}: {title}"

update_check_interval         0
shell_integration             enabled
allow_cloning                 ask
notify_on_cmd_finish          invisible 30 notify
term                          xterm-kitty
linux_display_server          wayland
wayland_enable_ime            yes
clear_all_shortcuts           yes

map kitty_mod+c               copy_to_clipboard
map cmd+c                     copy_or_noop
map kitty_mod+v               paste_from_clipboard

map cmd+v                     paste_from_clipboard
map kitty_mod+s               paste_from_selection

map shift+insert              paste_from_selection
map kitty_mod+o               pass_selection_to_program

map kitty_mod+k               scroll_line_up
map kitty_mod+j               scroll_line_down
map kitty_mod+page_up         scroll_page_up
map kitty_mod+page_down       scroll_page_down
map kitty_mod+home            scroll_to_prompt -1
map kitty_mod+end             scroll_to_prompt 1
map kitty_mod+h               show_scrollback
map kitty_mod+f               search_scrollback

map kitty_mod+n               new_window
map kitty_mod+k               close_window
map alt+down                  next_window
map kitty_mod+down            next_window
map alt+up                    previous_window
map kitty_mod+up              previous_window
map alt+ctrl+down             move_window_forward
map alt+ctrl+up               move_window_backward
map kitty_mod+space           move_window_to_top
map kitty_mod+r               start_resizing_window

map kitty_mod+1               first_window
map kitty_mod+2               second_window
map kitty_mod+3               third_window
map kitty_mod+4               fourth_window
map kitty_mod+5               fifth_window
map kitty_mod+6               sixth_window
map kitty_mod+7               seventh_window
map kitty_mod+8               eighth_window
map kitty_mod+9               ninth_window
map kitty_mod+0               tenth_window

map alt+right                 next_tab
map kitty_mod+right           ext_tab
map alt+left                  previous_tab
map kitty_mod+left            previous_tab
map kitty_mod+c               new_tab

map kitty_mod+x               close_tab
map kitty_mod+l               next_layout
map kitty_mod+\               goto_layout tall
map kitty_mod+-               goto_layout fat

map kitty_mod+/               command_palette
