include ~/.config/kitty/theme.conf

background_blur 1
background_opacity 0.9
copy_on_select yes
cursor_shape beam
cursor_trail 1
cursor_trail_start_threshold 0
font_family Maple Mono NF CN
hide_window_decorations no
scrollback_lines 50000
shell /run/current-system/profile/bin/fish
shell_integration enabled
wheel_scroll_multiplier 3.0
window_padding_width 0
