# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

"$schema" = "https://starship.rs/config-schema.json"
format = "[](red)$os$username[](bg:yellow fg:red)$directory[](fg:yellow bg:cyan)$git_branch$git_status[](fg:cyan bg:blue)$c$cpp$rust$golang$nodejs$php$java$kotlin$haskell$python[](fg:blue bg:bright-black)$direnv$docker_context$conda$pixi[](fg:bright-black bg:bright-black)$time[ ](fg:bright-black)$line_break$character"

[c]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[character]
disabled = false
error_symbol = "[ ❯](bold red)"
success_symbol = "[ ❯](bold green)"
vimcmd_replace_one_symbol = "[<](bold magenta)"
vimcmd_replace_symbol = "[<](bold magenta)"
vimcmd_symbol = "[ ❯](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"

[conda]
format = "[[ $symbol( $environment) ](fg:blue bg:bright-black)]($style)"
style = "bg:bright-black"

[cpp]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[directory]
format = "[ $path ]($style)"
style = "fg:black bg:yellow"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Developer = "󰲋"
Documents = "󰈙"
Downloads = ""
Music = "󰝚"
Pictures = ""

[direnv]
disabled = false
format = "[[ $symbol $loaded/$allowed ](fg:cyan bg:bright-black)]($style)"
style = "bg:bright-black"
symbol = ""

[docker_context]
format = "[[ $symbol( $context) ](fg:blue bg:bright-black)]($style)"
style = "bg:bright-black"
symbol = ""

[git_branch]
format = "[[ $symbol $branch ](fg:black bg:cyan)]($style)"
style = "bg:cyan"
symbol = ""

[git_status]
format = "[[($all_status$ahead_behind )](fg:black bg:cyan)]($style)"
style = "bg:cyan"

[golang]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[haskell]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[java]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[kotlin]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[line_break]
disabled = false

[nodejs]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[os]
disabled = false
style = "bg:red fg:black"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
NixOS = "󱄅"
Pop = ""
Raspbian = "󰐿"
RedHatEnterprise = "󱄛"
Redhat = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[php]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[pixi]
format = "[[ ($version)](fg:red bg:bright-black)]($style)"
style = "bg:bright-black"

[python]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[rust]
format = "[[ $symbol( $version) ](fg:black bg:blue)]($style)"
style = "bg:blue"
symbol = ""

[time]
disabled = false
format = "[[  $time ](fg:white bg:bright-black)]($style)"
style = "bg:bright-black"
time_format = "%R"

[username]
format = "[ $user ]($style)"
show_always = true
style_root = "bg:red fg:black"
style_user = "bg:red fg:black"
