# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

"$schema" = "https://starship.rs/config-schema.json"
format = "  $os$username $directory $git_branch$git_status $c$cpp$rust$golang$nodejs$php$java$kotlin$haskell$python $direnv$docker_context$conda$pixi $time$line_break$character"

[c]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[character]
disabled = false
error_symbol = "[ ❯](bold red)"
success_symbol = "[ ❯](bold green)"
vimcmd_replace_one_symbol = "[<](bold magenta)"
vimcmd_replace_symbol = "[<](bold magenta)"
vimcmd_symbol = "[ ❯](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"

[conda]
format = "[ $symbol( $environment) ]($style)"
style = "fg:bright-black"
symbol = ""

[directory]
format = "[ $path ]($style)"
style = "fg:yellow"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Developer = "󰲋"
Documents = "󰈙"
Downloads = ""
Music = "󰝚"
Pictures = ""

[direnv]
disabled = false
format = "[ $symbol $loaded/$allowed ]($style)"
style = "fg:bright-black"
symbol = ""

[docker_context]
format = "[ $symbol( $context) ]($style)"
style = "fg:bright-black"
symbol = ""

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:cyan"
symbol = ""

[git_status]
format = "[($all_status$ahead_behind )]($style)"
style = "fg:cyan"

[golang]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[haskell]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[java]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[kotlin]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[line_break]
disabled = false

[nodejs]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[os]
disabled = false
style = "fg:green"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = ""
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
NixOS = "󱄅"
Pop = ""
Raspbian = "󰐿"
RedHatEnterprise = "󱄛"
Redhat = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[php]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[pixi]
format = "[ ($version)]($style)"
style = "fg:bright-black"

[python]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[rust]
format = "[ $symbol( $version) ]($style)"
style = "fg:blue"
symbol = ""

[time]
disabled = false
format = "[  $time ]($style)"
style = "fg:bright-black"
time_format = "%R"

[username]
format = "[ $user ]($style)"
show_always = true
style_root = "fg:green"
style_user = "fg:green"
