context.properties = {
    default.clock.quantum = 256
    default.clock.min-quantum = 32
    default.clock.max-quantum = 512

    default.clock.rate = 48000
    default.clock.allowed-rates = [ 44100 48000 88200 96000 ]

    default.clock.quantum-limit = 8192
}

context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level = -11
            rt.prio = 88
            rt.time.soft = 200000
            rt.time.hard = 200000
        }
    }
]
