# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

[language-server.ccls]
command = "ccls"

[language-server.jdtls]
command = "jdtls"

[language-server.pylsp]
command = "pylsp"
config.pylsp.plugins.black.enabled = true
config.pylsp.plugins.mypy.enabled = true
config.pylsp.plugins.rope.enabled = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = [
  "-style=file",
  "-assume-filename=%{buffer_name}",
] }
language-servers = ["ccls"]

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format", args = [
  "-style=file",
  "-assume-filename=%{buffer_name}",
] }
language-servers = ["ccls"]

[[language]]
name = "java"
auto-format = true
language-servers = ["jdtls"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "js-beautify", args = [
  "--stdin",
  "--indent-size",
  "2",
  "-",
] }

[[language]]
name = "jsonc"
auto-format = true
formatter = { command = "js-beautify", args = [
  "--stdin",
  "--indent-size",
  "2",
  "-",
] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = [
  "--quiet",
  "--stdin-filename",
  "%{buffer_name}",
  "-",
] }
language-servers = ["pylsp"]
