packages:
  - .
nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - dsh-context@0.49.0 || 0.53.3
  - '@opencode2dsh/dsh-plugin@0.3.2'
  - dsh-opencode-go@0.1.4
  - '@mars-sea/dsh-commandcode-provider@0.11.5'
allowBuilds:
  '@google/genai': false
  dsh-devin-cli@https://codeload.github.com/leewf/dsh-devin-cli/tar.gz/06a9c61de653d86e6e634a3cc4f12f6035623788: true
  esbuild: true
  node-pty: true
  protobufjs: false
