# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

[cursor]
style=beam

[csd]
preferred=none

[main]
include=~/.config/foot/initial-color-theme.ini
include=~/.config/foot/themes/noctalia

font=Maple Mono NF CN
shell=/run/current-system/profile/bin/fish
dpi-aware=yes
term=foot
selection-target=clipboard
pad=0x0

[mouse]
hide-when-typing=yes

[scrollback]
lines=50000
multiplier=3.0

[tweak]
grapheme-shaping=yes
