# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

[editor]
auto-format = true
bufferline = "multiple"
color-modes = true
cursorline = true
insert-final-newline = true
line-number = "absolute"
mouse = true
scrolloff = 8
soft-wrap.enable = false
trim-trailing-whitespace = false
true-color = true

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-ignore = true
hidden = false

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true
display-progress-messages = true

[editor.search]
smart-case = true
wrap-around = true

[editor.smart-tab]
enable = true

[editor.statusline]
center = ["version-control"]
left = ["mode", "spinner", "file-name", "diagnostics"]
mode.insert = "INS"
mode.normal = "NOR"
mode.select = "SEL"
right = ["selections", "position", "file-encoding", "file-type"]

[editor.whitespace]
render = "none"
