#!/usr/bin/env python3
"""
find_md_tables.py — locate markdown tables and outdated-path candidates.

Used by the single-source-doc-lint workflow. Two scanners:

1. `tables`: walks a root, returns every markdown file whose table row count
   >= --min-rows, plus the table's column headers and row count. Material for
   the "can this table be regenerated by a command?" judgment.

2. `paths`: greps a root for stale directory references (e.g. `enable/`
   when the real path is `immutable/`, or `stow/` vs `mutable/`). Configurable
   so the skill can adopt to other rename events.

Stdlib only. No filesystem mutation. No network.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

TABLE_ROW = re.compile(r'^\s*\|.*\|\s*$')
PATH_PATTERNS_DEFAULT = [
    r'\benable/agents\b',
    r'\benable/desktop\b',
    r'\benable/noctalia-suite\b',
    r'\benable/system\b',
    r'\benable/terminal\b',
    r'\benable/utilities\b',
    r'\bstow/agents\b',
    r'\bstow/desktop\b',
    r'\bdotfiles/disable/[^/]+\b',   # disable/ is the trash bin
]


def scan_tables(root: Path, min_rows: int) -> list[dict]:
    """Find every markdown file that contains a table with >= min_rows rows."""
    out: list[dict] = []
    for md in root.rglob('*.md'):
        if any(p in md.parts for p in ('.git', 'node_modules', '__pycache__')):
            continue
        try:
            text = md.read_text(encoding='utf-8', errors='replace')
        except OSError:
            continue
        rel = md.relative_to(root)
        # collect contiguous table blocks: header + separator + >= min_rows body rows
        lines = text.splitlines()
        i = 0
        while i < len(lines):
            if (TABLE_ROW.match(lines[i])
                    and i + 1 < len(lines)
                    and re.match(r'^\s*\|[\s\-:|]+\|\s*$', lines[i + 1])):
                header = lines[i]
                sep = lines[i + 1]
                body: list[str] = []
                j = i + 2
                while j < len(lines) and TABLE_ROW.match(lines[j]):
                    body.append(lines[j])
                    j += 1
                if len(body) >= min_rows:
                    out.append({
                        'file': str(rel),
                        'header': header.strip(),
                        'sep': sep.strip(),
                        'row_count': len(body),
                        'first_body_row': body[0].strip() if body else '',
                    })
                i = j
            else:
                i += 1
    return out


def scan_paths(root: Path, patterns: list[str]) -> list[dict]:
    """Grep for stale-path references in markdown / org / txt."""
    pats = [re.compile(p) for p in patterns]
    exts = {'.md', '.org', '.txt', '.rst'}
    out: list[dict] = []
    for path in root.rglob('*'):
        if not path.is_file() or path.suffix.lower() not in exts:
            continue
        if any(p in path.parts for p in ('.git', 'node_modules', '__pycache__')):
            continue
        try:
            text = path.read_text(encoding='utf-8', errors='replace')
        except OSError:
            continue
        rel = path.relative_to(root)
        for lineno, line in enumerate(text.splitlines(), 1):
            for pat in pats:
                if pat.search(line):
                    out.append({
                        'file': str(rel),
                        'line': lineno,
                        'match': pat.pattern,
                        'snippet': line.strip()[:200],
                    })
                    break
    return out


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest='cmd', required=True)

    pt = sub.add_parser('tables', help='find markdown tables with >= N rows')
    pt.add_argument('--root', required=True)
    pt.add_argument('--min-rows', type=int, default=5,
                    help='minimum body rows to count as a "large" table (default 5)')
    pt.add_argument('--json', action='store_true')
    pt.set_defaults(min_rows=5)

    pp = sub.add_parser('paths', help='grep for stale path references')
    pp.add_argument('--root', required=True)
    pp.add_argument('--patterns', nargs='*', default=PATH_PATTERNS_DEFAULT,
                    help=f'regex patterns (default: {len(PATH_PATTERNS_DEFAULT)} built-in rename patterns)')
    pp.add_argument('--json', action='store_true')

    args = p.parse_args()

    if args.cmd == 'tables':
        root = Path(args.root).expanduser().resolve()
        rows = scan_tables(root, args.min_rows)
    else:
        root = Path(args.root).expanduser().resolve()
        rows = scan_paths(root, args.patterns)

    if args.json:
        json.dump(rows, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write('\n')
        return

    print(f'# {len(rows)} hit(s) under {root}')
    for r in rows:
        if args.cmd == 'tables':
            print(f"{r['file']:60}  rows={r['row_count']:>3}  "
                  f"header={r['header'][:50]}")
        else:
            print(f"{r['file']}:{r['line']:>4}  [{r['match']}]  {r['snippet']}")


if __name__ == '__main__':
    main()