(define %emacs-packages-list
  (cons* (specs->pkgs+out "emacs-pgtk"
                          "sbcl"

                          "emacs-consult"
                          "emacs-corfu"
                          "emacs-dashboard"
                          "emacs-ef-themes"
                          "emacs-embark"
                          "emacs-evil"
                          "emacs-evil-collection"
                          "emacs-geiser"
                          "emacs-geiser-guile"
                          "emacs-kotlin-mode"
                          "emacs-marginalia"
                          "emacs-orderless"
                          "emacs-sly"
                          "emacs-treemacs"
                          "emacs-vertico"
                          "emacs-vterm"
                          "emacs-which-key"
                          "emacs-yasnippet"

                          "tree-sitter"
                          "tree-sitter-bash"
                          "tree-sitter-c"
                          "tree-sitter-cpp"
                          "tree-sitter-css"
                          "tree-sitter-dockerfile"
                          "tree-sitter-go"
                          "tree-sitter-html"
                          "tree-sitter-javascript"
                          "tree-sitter-json"
                          "tree-sitter-python"
                          "tree-sitter-rust"
                          "tree-sitter-typescript")))
