# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0

[colors]
alpha=0.95

[cursor]
style=beam

[csd]
preferred=none

[main]
include=~/.config/foot/themes/noctalia
font=Maple Mono NF CN
shell=/run/current-system/profile/bin/fish
dpi-aware=yes
term=foot
selection-target=clipboard
pad=0x0

[mouse]
hide-when-typing=yes

[scrollback]
lines=50000
multiplier=3.0

[tweak]
grapheme-shaping=yes
font-monospace-warn=no

[key-bindings]
# 禁用与 Tmux 冲突的滚动键（让 Tmux 接管）
scrollback-up-page=none
scrollback-down-page=none

# 禁用复制粘贴（统一用 Tmux）
clipboard-copy=none
clipboard-paste=none
primary-paste=none
